# Generated by Django 2.2.6 on 2019-10-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='name')),
                ('number', models.PositiveIntegerField(default='', verbose_name='administration number')),
                ('adress', models.CharField(default='', max_length=20, verbose_name='Administration adress')),
            ],
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(default='', max_length=20, verbose_name='Teacher name')),
                ('teacher_number', models.PositiveIntegerField(default='', verbose_name='Teacher number')),
                ('teacher_lesson', models.CharField(default='', max_length=20, verbose_name='Teacher lesson')),
                ('teacher_history', models.TextField(default='', verbose_name='Teacher history')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='University name')),
                ('region', models.CharField(default='', max_length=20, verbose_name='University region')),
                ('category', models.CharField(default='', max_length=20, verbose_name='University category')),
                ('ort_porog', models.PositiveIntegerField(default='', verbose_name='Your ort')),
                ('prize', models.PositiveIntegerField(default='', verbose_name='What prize do you want?')),
                ('examination_examples', models.TextField(default='', verbose_name='Examination examples')),
                ('administration', models.ManyToManyField(to='student.Administration')),
                ('teachers', models.ManyToManyField(to='student.Teachers')),
            ],
        ),
    ]
