# Generated by Django 2.2.6 on 2019-10-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administration',
            name='number',
            field=models.CharField(default='', max_length=20, verbose_name='administration number'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='teacher_number',
            field=models.CharField(default='', max_length=20, verbose_name='Teacher number'),
        ),
    ]
