# Generated by Django 2.2.6 on 2019-11-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20191030_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='ort_porog',
            field=models.PositiveIntegerField(default='', verbose_name='Min Ort'),
        ),
        migrations.AlterField(
            model_name='university',
            name='prize',
            field=models.PositiveIntegerField(default='', verbose_name='Study prize'),
        ),
    ]
