# Generated by Django 2.2.6 on 2019-11-05 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0004_auto_20191101_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='About',
            field=models.TextField(default='', verbose_name='About University'),
        ),
        migrations.AddField(
            model_name='university',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
