# Generated by Django 2.2.6 on 2019-11-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20191105_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administration',
            name='owner1',
        ),
        migrations.RemoveField(
            model_name='teachers',
            name='owner2',
        ),
    ]
