# Generated by Django 2.2.6 on 2019-11-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20191105_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='About',
        ),
        migrations.AddField(
            model_name='university',
            name='about',
            field=models.TextField(default='', verbose_name='About University'),
        ),
    ]
