# Generated by Django 2.2.6 on 2019-11-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20191105_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='about',
        ),
    ]
