# Generated by Django 2.2.6 on 2019-11-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20191105_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='prize',
            field=models.PositiveIntegerField(default='', verbose_name='Study prize(som)'),
        ),
    ]
