# Generated by Django 2.2.6 on 2019-11-15 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0012_auto_20191106_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='VUZY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=1000, verbose_name='University name')),
                ('about', models.TextField(default='', verbose_name='About University')),
                ('region', models.CharField(default='', max_length=100, verbose_name='University region')),
                ('category', models.CharField(choices=[('1', 'All'), ('2', 'Medical'), ('3', 'Gumanytarian'), ('4', 'STEM')], default='', max_length=20, verbose_name='University category')),
                ('ort_porog', models.PositiveIntegerField(default='', verbose_name='Min Ort')),
                ('prize', models.PositiveIntegerField(default='', verbose_name='Study prize(som)')),
                ('examination_examples', models.TextField(default='', verbose_name='Examination examples')),
                ('administration', models.ManyToManyField(to='student.Administration')),
                ('owner', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('teachers', models.ManyToManyField(to='student.Teachers')),
            ],
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
