# Generated by Django 2.2.6 on 2019-11-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20191115_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='vuzy',
            name='date',
            field=models.DateField(default='', max_length=20, verbose_name='date of delivery'),
        ),
        migrations.AddField(
            model_name='vuzy',
            name='date1',
            field=models.DateField(default='', max_length=1000, verbose_name='Last day of delivery'),
        ),
        migrations.AddField(
            model_name='vuzy',
            name='requer',
            field=models.TextField(default='', verbose_name='What you need for admission'),
        ),
    ]
