# Generated by Django 2.2.6 on 2019-11-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20191115_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vuzy',
            name='requer',
        ),
        migrations.AddField(
            model_name='vuzy',
            name='need',
            field=models.TextField(default='', verbose_name='What you need for admission'),
        ),
    ]
